### PR TITLE
Update scalafmt plugin.

### PR DESCRIPTION
**Pull request by jeschkies**

### CODE REVIEW

**Comment by timcharper** [comment]
Exit status 1 when running "sbt scalafmtCheck test:scalafmtCheck"

<details>
<summary>Details</summary>
<pre>
[error] missing setting &#39;version&#39;. To fix this problem, add the following line to .scalafmt.conf: &#39;version=2.5.2&#39;.: /home/travis/build/mesosphere/usi/.scalafmt.conf
[error] missing setting &#39;version&#39;. To fix this problem, add the following line to .scalafmt.conf: &#39;version=2.5.2&#39;.: /home/travis/build/mesosphere/usi/.scalafmt.conf
[error] missing setting &#39;version&#39;. To fix this problem, add the following line to .scalafmt.conf: &#39;version=2.5.2&#39;.: /home/travis/build/mesosphere/usi/.scalafmt.conf
[error] (test-utils / Compile / scalafmtCheck) missing setting &#39;version&#39;. To fix this problem, add the following line to .scalafmt.conf: &#39;version=2.5.2&#39;.: /home/travis/build/mesosphere/usi/.scalafmt.conf
[error] (mesos-client / Compile / scalafmtCheck) missing setting &#39;version&#39;. To fix this problem, add the following line to .scalafmt.conf: &#39;version=2.5.2&#39;.: /home/travis/build/mesosphere/usi/.scalafmt.conf
[error] (metrics / Compile / scalafmtCheck) missing setting &#39;version&#39;. To fix this problem, add the following line to .scalafmt.conf: &#39;version=2.5.2&#39;.: /home/travis/build/mesosphere/usi/.scalafmt.conf
[error] (examples-keep-alive-framework / Compile / scalafmtCheck) missing setting &#39;version&#39;. To fix this problem, add the following line to .scalafmt.conf: &#39;version=2.5.2&#39;.: /home/travis/build/mesosphere/usi/.scalafmt.conf
[error] (examples-mesos-client-example / Compile / scalafmtCheck) missing setting &#39;version&#39;. To fix this problem, add the following line to .scalafmt.conf: &#39;version=2.5.2&#39;.: /home/travis/build/mesosphere/usi/.scalafmt.conf
[error] (persistence-zookeeper / Compile / scalafmtCheck) missing setting &#39;version&#39;. To fix this problem, add the following line to .scalafmt.conf: &#39;version=2.5.2&#39;.: /home/travis/build/mesosphere/usi/.scalafmt.conf
[error] (examples-core-hello-world / Compile / scalafmtCheck) missing setting &#39;version&#39;. To fix this problem, add the following line to .scalafmt.conf: &#39;version=2.5.2&#39;.: /home/travis/build/mesosphere/usi/.scalafmt.conf
[error] (mesos-master-detector / Compile / scalafmtCheck) missing setting &#39;version&#39;. To fix this problem, add the following line to .scalafmt.conf: &#39;version=2.5.2&#39;.: /home/travis/build/mesosphere/usi/.scalafmt.conf
[error] (core-models / Compile / scalafmtCheck) missing setting &#39;version&#39;. To fix this problem, add the following line to .scalafmt.conf: &#39;version=2.5.2&#39;.: /home/travis/build/mesosphere/usi/.scalafmt.conf
[error] (core / Compile / scalafmtCheck) missing setting &#39;version&#39;. To fix this problem, add the following line to .scalafmt.conf: &#39;version=2.5.2&#39;.: /home/travis/build/mesosphere/usi/.scalafmt.conf
[error] (metrics-dropwizard / Compile / scalafmtCheck) missing setting &#39;version&#39;. To fix this problem, add the following line to .scalafmt.conf: &#39;version=2.5.2&#39;.: /home/travis/build/mesosphere/usi/.scalafmt.conf
[error] (examples-simple-hello-world / Compile / scalafmtCheck) missing setting &#39;version&#39;. To fix this problem, add the following line to .scalafmt.conf: &#39;version=2.5.2&#39;.: /home/travis/build/mesosphere/usi/.scalafmt.conf
[error] (persistence / Compile / scalafmtCheck) missing setting &#39;version&#39;. To fix this problem, add the following line to .scalafmt.conf: &#39;version=2.5.2&#39;.: /home/travis/build/mesosphere/usi/.scalafmt.conf
[error] (Compile / scalafmtCheck) missing setting &#39;version&#39;. To fix this problem, add the following line to .scalafmt.conf: &#39;version=2.5.2&#39;.: /home/travis/build/mesosphere/usi/.scalafmt.conf
[error] Total time: 1 s, completed Jun 10, 2020 10:53:04 AM

restoring stty: 500:5:bf:8a3b:3:1c:7f:15:4:0:1:0:11:13:1a:0:12:f:17:16:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0
</pre>
</details>

**Comment by timcharper** [comment]
Exit status 1 when running "sbt scalafmtCheck test:scalafmtCheck"

<details>
<summary>Details</summary>
<pre>
[warn] /home/travis/build/mesosphere/usi/core/src/test/scala/com/mesosphere/usi/core/helpers/MockedFactory.scala isn&#39;t formatted properly!
[warn] /home/travis/build/mesosphere/usi/core/src/test/scala/com/mesosphere/usi/core/matching/RangeResourceMatcherTest.scala isn&#39;t formatted properly!
[warn] /home/travis/build/mesosphere/usi/core/src/test/scala/com/mesosphere/usi/core/matching/ScalarResourceMatcherTest.scala isn&#39;t formatted properly!
[warn] /home/travis/build/mesosphere/usi/core/src/test/scala/com/mesosphere/usi/core/FlowHelpersTest.scala isn&#39;t formatted properly!
[warn] /home/travis/build/mesosphere/usi/core/src/test/scala/com/mesosphere/usi/core/revive/SuppressReviveHandlerTest.scala isn&#39;t formatted properly!
[warn] /home/travis/build/mesosphere/usi/core/src/test/scala/com/mesosphere/usi/core/SchedulerTest.scala isn&#39;t formatted properly!
[warn] /home/travis/build/mesosphere/usi/core/src/test/scala/com/mesosphere/usi/core/SchedulerLogicHandlerTest.scala isn&#39;t formatted properly!
[warn] /home/travis/build/mesosphere/usi/core/src/test/scala/com/mesosphere/usi/core/helpers/MesosMock.scala isn&#39;t formatted properly!
[warn] /home/travis/build/mesosphere/usi/core/src/test/scala/com/mesosphere/usi/core/builders/SpecBuilderTest.scala isn&#39;t formatted properly!
[error] 2 files must be formatted
[error] 1 files must be formatted
[error] 1 files must be formatted
[error] 13 files must be formatted
[error] (mesos-client / Test / scalafmtCheck) 2 files must be formatted
[error] (persistence-zookeeper / Test / scalafmtCheck) 1 files must be formatted
[error] (examples-core-hello-world / Test / scalafmtCheck) 1 files must be formatted
[error] (core / Test / scalafmtCheck) 13 files must be formatted
[error] Total time: 2 s, completed Jun 10, 2020 11:07:24 AM

restoring stty: 500:5:bf:8a3b:3:1c:7f:15:4:0:1:0:11:13:1a:0:12:f:17:16:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0
</pre>
</details>

**Comment by jeschkies** [comment]
@timcharper this is related to https://github.com/mesosphere/marathon/pull/7193

**Review by pierrebeitz — APPROVED** [review]
LGTM!

added a commit formatting `build.sbt` as well. 
feel free to remove, fixup or squash that commit as you see fit.

**Pull request merged**
